version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/test
    depends_on:
      - mongodb
    networks:
      - app-network
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
